server:
  port: 7002
eureka:
  server:
    #自我保护机制
   enable-self-preservation: true
   renewal-percent-threshold: 0.49
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称
      #定义每分钟发送到服务器的更新数 每30秒续订一次
    lease-renewal-interval-in-seconds: 2
  client:
    register-with-eureka: false #false表示不会向注册中心注册自己
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
