server:
  port: 8010
spring:
  application:
    name: oauth2-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://120.53.125.32:3307/xxl_job?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: dlf123


  redis:
    host: 120.53.125.32
    port: 6380
    password: dlf123
    database: 0

eureka:
  client:
    #标识是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡。
    fetch-registry: true
    service-url:
      #集群版 http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
      defaultZone: http://120.53.125.32:7001/eureka
  instance:
    instance-id: stateMachine_test8006
    #访问路径可以显示ip
    prefer-ip-address: true
    #心跳检测与续约时间
    #开发时设置小些，保证服务关闭后注册中心能及时剔除服务。
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后的等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2


##consul的注册地址
jwt:
  config:
    key: dinglongfei
    ttl: 3600000

security:
  oauth2:
    resource:
      filter-order: 3